# Generated by Django 5.1.1 on 2024-09-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VintageEntry',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('era', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
                ('stock', models.IntegerField(default=1)),
            ],
        ),
    ]
