# Generated by Django 5.1.1 on 2024-09-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_additionalentry_delete_vintageentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalentry',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
