# Generated by Django 5.1.1 on 2024-09-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_additionalentry_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalentry',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
    ]
