# Generated by Django 5.1.1 on 2024-09-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_additionalentry_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalentry',
            old_name='era',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='additionalentry',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='additionalentry',
            name='name',
        ),
        migrations.RemoveField(
            model_name='additionalentry',
            name='price',
        ),
    ]
