# Generated by Django 5.1.1 on 2024-09-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_additionalentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalentry',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
