# Generated by Django 5.1.1 on 2024-09-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_additionalentry_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='additional_images/'),
        ),
    ]
